config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/new'
  # get 'bookmarks/create'
  # get 'bookmarks/destroy'
  # get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "lists#index"

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
  validates :list_id, presence: true, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    @bookmark = Bookmark.new
    @movie = Movie.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def destroy
  #   @bookmark = Bookmark.find(params[:id])
  #   @bookmark.destroy
  #   redirect_to list_path(@bookmark.list), status: :see_other
  # end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>What bookmark would you like to add?</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

<%= link_to "Return to your list", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All your lists:</h1>

<%= link_to "Create new list", new_list_path %>

<div>
  <% @lists.each do |list| %>
  <%# <p><%= list.bookmarks.first.movie.poster_url if list.bookmarks.count > 0 %>
  <%# <% if list.bookmarks.count > 0  %>
   <%# <%= link_to (image_tag list.bookmarks.first.movie.poster_url, alt:"Movie Poster", width: 200), list_path(list) %>
    <p><%= link_to list.name, list_path(list) %></p>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>What list would you like to add?</h1>

<div>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to "Back to your lists", lists_path %>
<%= link_to "Add a boomark",  new_list_bookmark_path(@list) %>

<div>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-trip">
      <img src=<%=bookmark.movie.poster_url%> />
      <div class="card-trip-infos">
        <div>
          <h2><%=bookmark.movie.title%></h2>
          <p><%=bookmark.movie.overview%></p>
          <%= link_to "🗑",
            bookmark_path(bookmark),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
           %>
        </div>
      </div>
    </div>
  <% end %>
</div>